name: Build & push container image

on:
  push:
    branches: test

env:
  DOCKER_IMAGE: ghcr.io/chuhlomin/blogengine-docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push to CR
        uses: chuhlomin/actions/docker-build-push@main
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}
          image_name: ${{ env.DOCKER_IMAGE }}
          tags: ${{ env.DOCKER_IMAGE }}:${{ github.sha }}
